version: '3'

volumes:
  todos-postgres:
    driver: local

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - todos-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=superpasswd

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
